/*
  The furniture of the hall: potted plants, benches and a runner down the
  middle. None of it is interactive and none of it moves — it exists so the
  long stretches of wall between frames read as a room somebody keeps rather
  than a corridor generated by a for-loop.

  Like the frames, everything here is instanced: one InstancedMesh per part
  across every plant in the hall, so a dozen planters cost a handful of draw
  calls. Terracotta, walnut and wool are materials in the same sense gilt and
  brass are — the palette's five tints stay reserved for the light over each
  frame and the ceiling above it.
*/

import * as THREE from "three";
import { makeCanvas } from "./textures";

export interface PropSpot {
  /** Which wall: -1 left, +1 right. */
  side: -1 | 1;
  z: number;
  /** Cycles the planting so no two neighbours match. */
  variant: number;
}

export interface PropsOptions {
  hallWidth: number;
  plants: PropSpot[];
  benches: PropSpot[];
  /** Runner: from zStart (near) to zEnd (far). Omit for a bare floor. */
  runner?: { zStart: number; zEnd: number; width: number };
}

/* A deterministic PRNG, so the planting is the same on every visit. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Woven wool: a flat weave with a slubby grain. One tile = 1 m. */
function runnerCanvas(): HTMLCanvasElement {
  const size = 256;
  const c = makeCanvas(size, size);
  const ctx = c.getContext("2d");
  if (!ctx) throw new Error("2D canvas unavailable");
  const rnd = mulberry32(41);

  ctx.fillStyle = "#5e4739";
  ctx.fillRect(0, 0, size, size);
  // Warp and weft: a fine grid, the weft a shade darker.
  for (let i = 0; i < size; i += 3) {
    ctx.fillStyle = "rgba(255,235,210,0.05)";
    ctx.fillRect(i, 0, 1, size);
    ctx.fillStyle = "rgba(0,0,0,0.10)";
    ctx.fillRect(0, i, size, 1);
  }
  // Slub: short irregular lighter threads.
  for (let i = 0; i < 1800; i++) {
    ctx.fillStyle = rnd() > 0.5 ? "rgba(226,196,150,0.10)" : "rgba(0,0,0,0.10)";
    ctx.fillRect(rnd() * size, rnd() * size, 1 + rnd() * 4, 1);
  }
  return c;
}

/**
 * The hall's furniture as one disposable object. `group` goes into the scene;
 * `setTheme` re-tints the wool for the dark palette.
 */
export class Props {
  readonly group = new THREE.Group();

  private readonly geometries: THREE.BufferGeometry[] = [];
  private readonly materials: THREE.Material[] = [];
  private readonly textures: THREE.Texture[] = [];
  private readonly runnerMat: THREE.MeshStandardMaterial | null = null;

  constructor(opts: PropsOptions) {
    const rnd = mulberry32(17);

    /* ---- materials --------------------------------------------------- */
    const terracotta = this.mat(
      new THREE.MeshStandardMaterial({
        color: new THREE.Color("#b06845"),
        roughness: 0.85,
        metalness: 0,
      })
    );
    const soil = this.mat(
      new THREE.MeshStandardMaterial({ color: new THREE.Color("#2a1f18"), roughness: 1 })
    );
    // Two greens, both low-chroma: the corridor is lit warm and a nursery
    // green would be the loudest thing in it.
    const leafDark = this.mat(
      new THREE.MeshStandardMaterial({
        color: new THREE.Color("#33482f"),
        roughness: 0.72,
        metalness: 0,
        side: THREE.DoubleSide,
      })
    );
    const leafLight = this.mat(
      new THREE.MeshStandardMaterial({
        color: new THREE.Color("#4d6338"),
        roughness: 0.66,
        metalness: 0,
        side: THREE.DoubleSide,
      })
    );
    const walnut = this.mat(
      new THREE.MeshStandardMaterial({
        color: new THREE.Color("#4a3120"),
        roughness: 0.55,
        metalness: 0,
      })
    );
    const iron = this.mat(
      new THREE.MeshStandardMaterial({
        color: new THREE.Color("#1d1a18"),
        roughness: 0.45,
        metalness: 0.6,
      })
    );

    /* ---- geometry ---------------------------------------------------- */
    const potGeo = this.geo(new THREE.CylinderGeometry(0.17, 0.125, 0.3, 18, 1));
    const rimGeo = this.geo(new THREE.CylinderGeometry(0.185, 0.185, 0.045, 18, 1));
    const soilGeo = this.geo(new THREE.CircleGeometry(0.155, 18));
    // One blade, standing on its base: scaled per instance into a snake
    // plant's sword or a palm's frond.
    const bladeGeo = this.geo(new THREE.ConeGeometry(0.05, 1, 4, 1, false));
    bladeGeo.translate(0, 0.5, 0);
    bladeGeo.scale(1, 1, 0.22);

    const seatGeo = this.geo(new THREE.BoxGeometry(1.15, 0.055, 0.36));
    const legGeo = this.geo(new THREE.BoxGeometry(0.05, 0.42, 0.3));

    const plants = opts.plants;
    const pots = new THREE.InstancedMesh(potGeo, terracotta, Math.max(1, plants.length));
    const rims = new THREE.InstancedMesh(rimGeo, terracotta, Math.max(1, plants.length));
    const soils = new THREE.InstancedMesh(soilGeo, soil, Math.max(1, plants.length));
    const BLADES = 11;
    const bladesDark = new THREE.InstancedMesh(bladeGeo, leafDark, Math.max(1, plants.length * BLADES));
    const bladesLight = new THREE.InstancedMesh(bladeGeo, leafLight, Math.max(1, plants.length * BLADES));

    const m = new THREE.Matrix4();
    const q = new THREE.Quaternion();
    const e = new THREE.Euler();
    const p = new THREE.Vector3();
    const s = new THREE.Vector3();
    const flat = new THREE.Vector3(1, 1, 1);
    let dark = 0;
    let light = 0;

    plants.forEach((spot, i) => {
      // Tucked against the wall so a visitor pressed to the wall walks past
      // rather than through the foliage.
      const x = spot.side * (opts.hallWidth / 2 - 0.24);
      const glazedPot = spot.variant % 2 === 1;
      if (glazedPot) {
        // Instancing shares one material per mesh, so a glazed planter is
        // the same pot under a different colour: swap by tinting.
        pots.setColorAt(i, new THREE.Color("#5d6f66"));
        rims.setColorAt(i, new THREE.Color("#5d6f66"));
      } else {
        pots.setColorAt(i, new THREE.Color(1, 1, 1));
        rims.setColorAt(i, new THREE.Color(1, 1, 1));
      }

      m.compose(p.set(x, 0.15, spot.z), new THREE.Quaternion(), flat);
      pots.setMatrixAt(i, m);
      m.compose(p.set(x, 0.288, spot.z), new THREE.Quaternion(), flat);
      rims.setMatrixAt(i, m);
      m.compose(
        p.set(x, 0.302, spot.z),
        q.setFromEuler(e.set(-Math.PI / 2, 0, 0)),
        flat
      );
      soils.setMatrixAt(i, m);

      // Two plantings. The upright takes tall narrow swords; the spreading
      // one takes shorter fronds thrown wide.
      const upright = spot.variant % 2 === 0;
      const height = upright ? 0.95 : 0.6;
      const lean = upright ? 0.16 : 0.62;
      for (let b = 0; b < BLADES; b++) {
        const a = (b / BLADES) * Math.PI * 2 + rnd() * 0.4;
        const tilt = lean * (0.45 + rnd() * 0.75);
        const len = height * (0.6 + rnd() * 0.55);
        const wide = upright ? 0.7 + rnd() * 0.5 : 1.1 + rnd() * 0.7;
        q.setFromEuler(e.set(0, a, tilt, "YZX"));
        m.compose(
          p.set(x + Math.cos(a) * 0.03, 0.3, spot.z + Math.sin(a) * 0.03),
          q,
          s.set(wide, len, wide)
        );
        const pale = (b + spot.variant) % 3 === 0;
        if (pale) bladesLight.setMatrixAt(light++, m);
        else bladesDark.setMatrixAt(dark++, m);
      }
    });
    bladesDark.count = Math.max(dark, 0);
    bladesLight.count = Math.max(light, 0);
    for (const mesh of [pots, rims, soils, bladesDark, bladesLight]) {
      mesh.instanceMatrix.needsUpdate = true;
      if (mesh.instanceColor) mesh.instanceColor.needsUpdate = true;
    }
    if (plants.length) this.group.add(pots, rims, soils, bladesDark, bladesLight);

    /* ---- benches ------------------------------------------------------ */
    const benches = opts.benches;
    if (benches.length) {
      const seats = new THREE.InstancedMesh(seatGeo, walnut, benches.length);
      const legs = new THREE.InstancedMesh(legGeo, iron, benches.length * 2);
      benches.forEach((spot, i) => {
        const x = spot.side * (opts.hallWidth / 2 - 0.23);
        m.compose(p.set(x, 0.45, spot.z), new THREE.Quaternion(), flat);
        seats.setMatrixAt(i, m);
        for (let k = 0; k < 2; k++) {
          const dz = (k === 0 ? -1 : 1) * 0.44;
          m.compose(p.set(x, 0.21, spot.z + dz), new THREE.Quaternion(), flat);
          legs.setMatrixAt(i * 2 + k, m);
        }
      });
      seats.instanceMatrix.needsUpdate = true;
      legs.instanceMatrix.needsUpdate = true;
      this.group.add(seats, legs);
    }

    /* ---- runner ------------------------------------------------------- */
    if (opts.runner) {
      const { zStart, zEnd, width } = opts.runner;
      const length = zStart - zEnd;
      const tex = new THREE.CanvasTexture(runnerCanvas());
      tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
      tex.colorSpace = THREE.SRGBColorSpace;
      tex.repeat.set(width, length);
      tex.anisotropy = 8;
      this.textures.push(tex);

      const geo = this.geo(new THREE.PlaneGeometry(width, length));
      const mat = this.mat(
        new THREE.MeshStandardMaterial({ map: tex, roughness: 0.95, metalness: 0 })
      ) as THREE.MeshStandardMaterial;
      this.runnerMat = mat;
      const rug = new THREE.Mesh(geo, mat);
      rug.rotation.x = -Math.PI / 2;
      rug.position.set(0, 0.004, (zStart + zEnd) / 2);

      // Two brass guard stripes just inside the selvedge.
      const stripeGeo = this.geo(new THREE.PlaneGeometry(0.022, length));
      const stripeMat = this.mat(
        new THREE.MeshStandardMaterial({
          color: new THREE.Color("#8a7440"),
          roughness: 0.7,
          metalness: 0.15,
        })
      );
      for (const sx of [-1, 1]) {
        const stripe = new THREE.Mesh(stripeGeo, stripeMat);
        stripe.rotation.x = -Math.PI / 2;
        stripe.position.set(sx * (width / 2 - 0.075), 0.0055, (zStart + zEnd) / 2);
        this.group.add(stripe);
      }
      this.group.add(rug);
    }
  }

  /** The wool reads too dark against a dark floor; lift it a shade. */
  setTheme(dark: boolean): void {
    this.runnerMat?.color.set(dark ? "#c8b6a6" : "#ffffff");
  }

  dispose(): void {
    for (const g of this.geometries) g.dispose();
    for (const m of this.materials) m.dispose();
    for (const t of this.textures) t.dispose();
  }

  private geo<T extends THREE.BufferGeometry>(g: T): T {
    this.geometries.push(g);
    return g;
  }

  private mat<T extends THREE.Material>(m: T): T {
    this.materials.push(m);
    return m;
  }
}
